FROM php:5.6-cli-alpine

COPY ./xdbug-config.ini "${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini"
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

RUN apk add --no-cache $PHPIZE_DEPS
RUN pecl install xdebug-2.5.5
RUN docker-php-ext-enable xdebug
RUN apk del --no-cache $PHPIZE_DEPS

WORKDIR /var/www/html